# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: Raúl Murcia
# Description of the Site
description: Computer Science Student and Machine Learning Enthusiast
# URL of Image of the Site
site-image: /assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url:

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: rauloctaviomurcia@gmail.com
facebook_username:
twitter_username:
instagram_username:
linkedin_username: raúl-octavio-murcia-yocupicio-5ba13b19a
github_username:  raulmyocu
youtube_channel_id:
reddit_username:
behance_username:
dribbble_username:
spotify_username:

# Google Analytics
google-analytics:  #UA-163806439-1

# Disqus
disqus-shortname: raulmyocu

# Name of the Author
author-name: Raúl Murcia
# URL for the Image of the Author
author-image: https://media-exp1.licdn.com/dms/image/C5603AQG5xXyXO1gORg/profile-displayphoto-shrink_200_200/0?e=1606953600&v=beta&t=ZYQ-xuBRVEzfYZQVZXAkvVXTwX0sUQWiVS2qYs7Q5RI
# 60 Words About the Author
author-about: I am a computer science student at Universidad de Sonora, currently on my fourth year. My main interests are Artificial Intelligence, Theory of Computation and also fun math stuff.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/raulmyocu

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
